material_model: "NorSand"
reference_pressure: 100  # kPa

experimental_data:
  - type: "drained_100"
    filepath: "data/drained/100kPa.csv"
    cell_pressure: 100
    weight: 1.0

parameters:
  M_tc: [1.2, 1.8]    
  H_0:     [50, 300]    
  psi_0: [-0.05, 0.05]
  

optimization:
  method: "hybrid"
  max_iterations: 20

output:
  report_file: "results/calibration_report.html"